production:
  :concurrency: 5
:queues:
  - default
  - mailers# :schedule:
  #  an_scheduled_task:
  #    cron: '0 * * * * *'  # Runs once per minute
  #    class: ExampleJob
  #    args: ['a', 'b']
:scheduler:
  :schedule:
    scrapping_windguru:
      cron: '0 5 * * * *'  # Runs once per day at 5:00 AM
      class: ScrappingWindguruJob
      args: ['pichilemu']
