production:
  :concurrency: 5
:queues:
  - default
  - mailers# :schedule:
  #  an_scheduled_task:
  #    cron: '0 * * * * *'  # Runs once per minute
  #    class: ExampleJob
  #    args: ['a', 'b']
:scheduler:
  :schedule:
    scrapping_windguru_pichilemu:
      cron: '0 * * * * * America/Santiago'  # Runs per minute at 5:00 AM
      class: ScrappingWindguruJob
      args: 'pichilemu'
    scrapping_windguru_matanzas:
      cron: '0 * * * * * America/Santiago'  # Runs once per minute at 5:00 AM
      class: ScrappingWindguruJob
      args: 'matanzas'
    scrapping_windguru_puertecillo:
      cron: '0 * * * * * America/Santiago'  # Runs once per minute at 5:00 AM
      class: ScrappingWindguruJob
      args: 'puertecillo'
